import { useState, useEffect } from 'react';

interface ContentItem {
  type: string;
  title: string;
  excerpt: string;
  link: string;
  source: string;
  date: string;
  size?: string;
  audioLength?: string;
  audioUrl?: string;
  image?: string;
  views?: number;
}

interface ContentFeed {
  lastUpdated: string;
  content: ContentItem[];
}

export function useContentFeed() {
  const [content, setContent] = useState<ContentItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let isMounted = true;

    async function loadContent() {
      try {
        // Fetch pre-built content feed (generated by GitHub Actions)
        const url = new URL(`${import.meta.env.BASE_URL}content-feed.json`, location.origin);
        url.searchParams.set("v", __APP_VERSION__ || Date.now().toString());
        
        const response = await fetch(url.toString(), { cache: 'no-store' });
        
        if (!response.ok) {
          throw new Error('Failed to load content feed');
        }

        const feedData: ContentFeed = await response.json();

        if (!isMounted) return;

        if (!feedData.content || feedData.content.length === 0) {
          throw new Error('No content available');
        }

        // Content is already sorted by date in the feed
        setContent(feedData.content);
        setError(null);
      } catch (err) {
        console.error('Error loading content:', err);
        setError('Unable to load latest work. Please try again later.');
      } finally {
        if (isMounted) {
          setLoading(false);
        }
      }
    }

    loadContent();

    return () => {
      isMounted = false;
    };
  }, []);

  return { content, loading, error };
}

